update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -9,8 +9,8 @@ on:  # yamllint disable-line rule:truthy
         description: 'Version to release (major, minor, patch) Ex: 1.0.0'
         required: true
 jobs:
-  build-and-scan:
-    name: Build and Release
+  validate-and-prepare:
+    name: Validate Input and Prepare Release
     runs-on: ubuntu-latest
     steps:
       - name: Set Release version and branch name
@@ -21,7 +21,7 @@ jobs:
       - name: Validate version input
         run: |
           if [[ "$version" == "none" ]]; then
-            echo "Invalid version specified: $version Must follow major, minor, patch versioning."
+            echo "Invalid version specified: $version. Must follow major, minor, patch versioning."
             exit 1
           fi
         env:
@@ -33,49 +33,39 @@ jobs:
           ref: ${{ env.branch_name }}
           fetch-depth: 0
 
-#      - name: Set up Go
-#        uses: actions/setup-go@v5
-#        with:
-#          go-version: "1.23"
-
-      - name: Set up Git
-        run: |
-          git config --global user.name 'github-actions'
-          git config --global user.email 'github-actions@github.com'
-
       - name: Verify if release branch exists
         run: |
           echo "Checking if release branch '${{ env.branch_name }}' exists..."
           git fetch --all
-          echo "Listing all remote branches..."
-          git branch -r
           if git branch -r | grep "origin/${{ env.branch_name }}"; then
             echo "The branch ${{ env.branch_name }} exists."
           else
             echo "The branch ${{ env.branch_name }} does not exist."
+            exit 1
           fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Verify branch changes
         run: |
-          changes_made=false
           if git diff --quiet origin/main origin/${{ env.branch_name }}; then
-            echo "No changes detected between ${{ env.branch_name }} and main. Aborting.."
-            echo "changes_made=false" >> $GITHUB_ENV
+            echo "No changes detected between ${{ env.branch_name }} and main. Aborting."
             exit 1
-          else
-            echo "Changes detected. Proceeding for PR creation"
-            echo "changes_made=true" >> $GITHUB_ENV
           fi
-
-          echo "Commit log of ${{ env.branch_name }} compared to main:"
-          git log origin/main..origin/${{ env.branch_name }} --oneline
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # Create a Pull Request using GitHub CLI
-      - name: Create Pull Request using GitHub CLI
+  create-pull-request:
+    name: Create Pull Request
+    runs-on: ubuntu-latest
+    needs: validate-and-prepare
+    steps:
+      - name: Set up Git
+        run: |
+          git config --global user.name 'github-actions'
+          git config --global user.email 'github-actions@github.com'
+
+      - name: Create Pull Request
         run: |
           sed 's/A few sentences describing the overall goals of the pull request'"'"'s commits./Release v${{ env.version }}/' .github/pull_request_template.md > temp_release_pr_body.md
           gh pr create --title "Release v${{ env.version }}" \
@@ -88,7 +78,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Wait for PR to be merged
-        if: env.changes_made == 'true'
         run: |
           pr_number=$(gh pr list --base main --head ${{ env.branch_name }} --search "Release v${{ env.version }}" --json number --jq '.[0].number')
           if [ -z "$pr_number" ]; then
@@ -115,30 +104,36 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+  create-release:
+    name: Create Release
+    runs-on: ubuntu-latest
+    needs: create-pull-request
+    steps:
+      - name: Set up Git
+        run: |
+          git config --global user.name 'github-actions'
+          git config --global user.email 'github-actions@github.com'
+
       - name: Create new tag
         run: |
           git fetch --tags
           git tag v${{ env.version }}
           git push origin v${{ env.version }}
 
-      - name: Create Github Release
+      - name: Create Release
         id: create_release
-        uses: actions/create-release@v1
+        uses: softprops/action-gh-release@v2
         with:
           tag_name: v${{ env.version }}
           release_name: v${{ env.version }}
-          body: |
-            ### Documentation
-            - [General Documentation](https://dell.github.io/csm-docs/docs/)
-            ### Change Log
-            See the [CHANGELOG](https://github.com/dell/csm/blob/main/CHANGELOG/CHANGELOG-${{ env.version }}.md) for more details.
           draft: true
           prerelease: false
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Attach Built Binaries
-        run: |
-          gh release upload "v${{ env.version }}" csm/releases/download/v${{ env.version }}/dellctl
+          generate_release_notes: true
+          make_latest: true
+          body: |
+            ## Documentation
+            - [General Documentation](https://dell.github.io/csm-docs/docs/)
+            ## Change Log
+            See the [CHANGELOG](https://github.com/dell/csm/blob/main/CHANGELOG/CHANGELOG-${{ env.version }}.md) for more details.
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
