removed branch creation and push actions

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -32,10 +32,10 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: "1.23"
+#      - name: Set up Go
+#        uses: actions/setup-go@v5
+#        with:
+#          go-version: "1.23"
 
       - name: Set up Git
         run: |
@@ -50,12 +50,12 @@ jobs:
 #          git tag v${{ github.event.inputs.version }}
 #          git push origin v${{ github.event.inputs.version }}
 
-      - name: Create Release Branch
-        run: |
-          git checkout -b $branch_name
-          git push --set-upstream origin $branch_name
-        env:
-          branch_name: ${{ env.branch_name }}
+#      - name: Create Release Branch
+#        run: |
+#          git checkout -b $branch_name
+#          git push --set-upstream origin $branch_name
+#        env:
+#          branch_name: ${{ env.branch_name }}
 
 #      - name: Switch to Release Branch
 #        run: |
@@ -77,7 +77,8 @@ jobs:
           echo "Staging and commiting the CHANGELOG-$version.md"
           git add CHANGELOG-$version.md
           git commit -m "Update changelog for release v$version"
-          git push origin $branch_name
+          echo "changes_made=true" >> $GITHUB_ENV
+#          git push origin $branch_name
         env:
           version: ${{ env.version }}
           branch_name: ${{ env.branch_name }}
@@ -93,36 +94,38 @@ jobs:
 #        env:
 #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Verify branch changes
-        run: |
-          changes_made=true
-          if git diff --quiet main release-v${{ github.event.inputs.version }}; then
-            echo "No changes detected between release-v2.1.2 and main. Aborting."
-            echo "changes_made=false" >> $GITHUB_ENV
-            exit 1
-          else
-            echo "Changes detected. Proceeding for PR creation"
-            echo "changes_made=true" >> $GITHUB_ENV
-          fi
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#      - name: Verify branch changes
+#        run: |
+#          changes_made=true
+#          if git diff --quiet main release-v${{ github.event.inputs.version }}; then
+#            echo "No changes detected between release-v2.1.2 and main. Aborting.."
+#            echo "changes_made=false" >> $GITHUB_ENV
+#            exit 1
+#          else
+#            echo "Changes detected. Proceeding for PR creation"
+#            echo "changes_made=true" >> $GITHUB_ENV
+#          fi
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Switch back to base branch
-        if: env.changes_made == 'true'
-        run: |
-          echo "Switching back to base branch main"
-          git checkout main
-          echo "Current branch after switching back: $(git branch --show-current)"
+#      - name: Switch back to base branch
+#        if: env.changes_made == 'true'
+#        run: |
+#          echo "Switching back to base branch main"
+#          git checkout main
+#          echo "Current branch after switching back: $(git branch --show-current)"
 
       - name: Create Pull request
         if: env.changes_made == 'true'
-        uses: peter-evans/create-pull-request@v6
+        uses: peter-evans/create-pull-request@v7
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           branch: release-v${{ github.event.inputs.version }}
           base: test-release-main
+          commit-message: "Adding CHANGELOG file for new release ${{ env.version }}"
           title: "Release v${{ github.event.inputs.version }}"
           body: "This PR merges the release-v${{ github.event.inputs.version }} into main."
+          sign-commits: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
