debug

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -42,11 +42,22 @@ jobs:
           git tag v${{ github.event.inputs.version }}
           git push origin v${{ github.event.inputs.version }}
 
-      - name: Update Changelog
+      - name: Create Release Branch
         run: |
           git checkout -b release-v${{ github.event.inputs.version }}
-          echo "## [${{ github.event.inputs.version }}] - $(date +'%Y-%m-%d')" >> CHANGELOG-${{ github.event.inputs.version }}.md
+          git push --set-upstream origin release-v${{ github.event.inputs.version }}
+
+      - name: Switch to Release Branch
+        run: |
+          git checkout release-v${{ github.event.inputs.version }}
+          echo "Currently on branch: $(git branch --show-current)"
+
+      - name: Update and commit Changelog
+        run: |
+          echo "## [v${{ github.event.inputs.version }}] - $(date +'%Y-%m-%d')" >> CHANGELOG-${{ github.event.inputs.version }}.md
           echo "- Added new release." >> CHANGELOG-${{ github.event.inputs.version }}.md
+          cat CHANGELOG-${{ github.event.inputs.version }}.md
+          ls -l CHANGELOG-${{ github.event.inputs.version }}.md
           git add CHANGELOG-${{ github.event.inputs.version }}.md
           git commit -m "Update changelog for release v${{ github.event.inputs.version }}"
           git push origin release-v${{ github.event.inputs.version }}
@@ -60,6 +71,15 @@ jobs:
           git diff main...release-v${{ github.event.inputs.version }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Verify branch changes
+        run: |
+          if git diff --quiet main release-vv2.0.0; then
+            echo "No changes detected between release-vv2.0.0 and main. Aborting."
+            exit 1
+          else
+            echo "Changes detected. Proceeding with PR creation."
+          fi
 
       - name: Create Pull request
         uses: peter-evans/create-pull-request@v4
@@ -77,7 +97,7 @@ jobs:
         run: |
           echo "Waiting for the PR to be merged. Please merge the PR manually."
           while true; do
-            pr_status=$(gh pr view update-common-dependency --json state --jq '.state')
+            pr_status=$(gh pr view "release-v${{ github.event.inputs.version }}" --json state --jq '.state')
             if [ "$pr_status" = "MERGED" ]; then
               echo "PR has been merged."
               break
